### ISSUE TITLE
How to finetune on multiple geometries

### ISSUE THREAD

**Issue by RaulFD-creator** [mdsunivie/deeperwin#13]
Hi,

I have read the paper "Towards a Foundation Model for Neural Network Wavefunctions" and I was interested in how to run the fine-tuning of a pre-trained model/checkpoint against different geometries of the same molecule. I was thinking something similar to the Figure 5 in the paper. Could you indicate me how should I do so or how to construct the config file necessary?

Thanks beforehand!

**Comment by LeonGerBerlin** [comment]
Hi, 

thanks for your interest in our work. I am assuming you are able to run our code with minimal settings. 

To reproduce the figure: 
1. You need to download our pre-trained model checkpoints (https://doi.org/10.6084/m9.figshare.23585358.v1). The file "tinymol_v10_2023-02-26_18x20_500k.zip" accompanies the publication "Towards a Foundation Model for Neural Network Wavefunctions". 
2. I attached a zip file (reproduce_fig5.zip) containing two files: 

- config_reuse_template.yml: This a template config with pre-defined optimization settings we used.
- setup_finetuning_exp.py: A python file helping you to setup the calculations. I added the names of the datasets we used to generate the figure. It additionally overwrites the model settings in the config template to make sure you run with the correct settings. 
3. To run the calculations you need to make sure you set the right dataset name in the python file and the right path to the checkpoint, then just call: 
`python setup_finetuning_exp.py`

Please let me know if something is unclear or if you encounter any problems. 

Best regards

Leon

[reproduce_fig5.zip](https://github.com/mdsunivie/deeperwin/files/12683891/reproduce_fig5.zip)

**Comment by RaulFD-creator** [comment]
Thanks for the help!
