### ISSUE TITLE
error of pip install -e .

### ISSUE THREAD

**Issue by KingDamLiu** [mdsunivie/deeperwin#14]
Collecting orbax (from flax->deeperwin==1.2.0)
  Using cached orbax-0.1.9-py3-none-any.whl
  Using cached orbax-0.1.8.tar.gz (1.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]

      *** Orbax is a namespace, and not a standalone package. For model checkpointing and exporting utilities, please install `orbax-checkpoint` and `orbax-export` respectively (instead of `orbax`). ***

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by LeonGerBerlin** [comment]
Hey, 

thank you for your interest in our work. I am sorry for the inconvenience. I fixed the orbax version to `orbax==0.1.2`. This should fix the problem. 

Let me know if you still encounter any issues. 

Best,
Leon
