### ISSUE TITLE
`e3nn-jax` required but not listed in the setup.cfg (the most recent `e3nn-jax` cannot work)

### ISSUE THREAD

**Issue by sherrylixuecheng** [mdsunivie/deeperwin#9]
Hello all,

I would like to just report that there is a missing package `e3nn-jax` that should be included in the setup files. Also, since the `deeperwin` needs a specific jax version, which is different from the requirements of the current `e3nn-jax`, I guess it will be also great to label the specific version that is used in `deeperwin`.
I just closed the other issue I made since it is actually caused by using the most recent version of `e3nn-jax`. I downgraded to `e3nn-jax==0.11.0` and  the error flag of `"AttributeError: module 'jax.tree_util' has no attribute 'register_pytree_with_keys_class'"` disappears.
Thank you so much for your attention and help!
Best,
Sherry Cheng

**Comment by LeonGerBerlin** [comment]
Hi, 
thank you for your interest in our work! 
Sorry for the inconvenience, I updated the setup.cfg file and added missing packages including e3nn-jax==0.17.1 (the version we use internally). I also changed the kfac version. Make sure to use as well: 

`pip install --upgrade jax==0.3.23 jaxlib==0.3.22+cuda11.cudnn82 dm-haiku==0.0.9 flax==0.6.4 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
`

I tested it with a minimal config for python=3.8 on a GPU `(Driver Version: 510.85.02    CUDA Version: 11.6)`. I hope this should resolve all problems. Let me know if the problems remain. 

Best, 
Leon

**Comment by sherrylixuecheng** [comment]
Hi Leon,

Thank you so much for your update! Another package needs additional attention is `pydantic`, the most recent version is `2.0.3` and will cause errors. I tried the `1.10.11` and it seems remove the corresponding error.

I will keep trying using your setup and report again if I found anything else.
Best,
Sherry

**Comment by LeonGerBerlin** [comment]
Thanks for the help! I pinned the pydantic version.
